/* Super Admin commercial management. Authorization remains exclusively in the API. */
window.TAGCHECK_SUPERADMIN = {
  async mount(host, request, escape, back, refreshIdentity) {
    const panel = document.createElement('section');
    panel.id = 'superadminPanel'; panel.className = 'screen'; host.replaceChildren(panel);
    panel.innerHTML = '<div class="card panel">Carregando administração...</div>';
    let companies = [], users = [], links = [];
    const roles = {company_admin:'Administrador', supervisor:'Supervisor', operator:'Operador', viewer:'Somente leitura'};
    const badge = (active, on, off) => `<span class="status-pill ${active ? 'status-ok' : 'status-danger'}">${active ? on : off}</span>`;
    let editingCompany = null, editingUser = null;
    try {
      [companies, users] = await Promise.all([request('/companies'), request('/users')]);
      const find = selector => panel.querySelector(selector);
      const feedback = message => { const el = find('#superadminFeedback'); if (el) el.textContent = message; };
      const run = async (element, action) => { const controls = [...element.querySelectorAll('input,select,button')]; controls.forEach(x => x.disabled = true); feedback('Salvando...'); try { const message = await action(); if (message) feedback(message); else feedback('Operação concluída.'); } catch (e) { feedback(e.message); } finally { controls.forEach(x => x.disabled = false); } };
      const options = (items, label) => items.map(item => `<option value="${item.id}">${escape(label(item))}</option>`).join('');
      const render = () => {
        panel.innerHTML = `<div class="card panel"><div class="inline-actions"><h2>Super Admin</h2><button id="backToAdmin" class="outline-button">Voltar aos equipamentos</button></div><div id="superadminFeedback" role="status" aria-live="polite"></div></div>
        <div class="grid-2 superadmin-grid"><div class="card panel"><h3>Empresas</h3><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Identificador</th><th>Status</th><th>Ações</th></tr></thead><tbody id="companyRows"></tbody></table></div><form id="companyCreateForm" class="login-stack"><label>Nome<input class="input" name="name" required maxlength="200"></label><label>Identificador<input class="input" name="slug" required maxlength="100" pattern="[a-z0-9]+(-[a-z0-9]+)*"></label><button class="primary-button">Criar empresa</button></form></div>
        <div class="card panel"><h3>Usuários</h3><div class="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Status</th><th>Ações</th></tr></thead><tbody id="userRows"></tbody></table></div><form id="userCreateForm" class="login-stack" autocomplete="off"><label>Nome<input class="input" name="name" required maxlength="200"></label><label>E-mail<input class="input" name="email" type="email" required maxlength="254"></label><label>Senha inicial (mínimo de 12 caracteres)<input class="input" name="password" type="password" required minlength="12" maxlength="1024" autocomplete="new-password"></label><button class="primary-button">Criar usuário</button></form></div></div>
        <div id="globalCompanySettings" class="card panel hidden"></div><div class="card panel"><h3>Vínculo usuário / empresa</h3><form id="membershipForm" class="login-stack"><label>Usuário<select id="memberUser" class="input" required></select></label><label>Empresa<select id="memberCompany" class="input" required></select></label><label>Papel<select id="memberRole" class="input" required>${Object.entries(roles).map(([value,label]) => `<option value="${value}">${label}</option>`).join('')}</select></label><label><input id="memberActive" type="checkbox" checked> Vínculo ativo</label><p id="membershipStatus"></p><button id="saveMembership" class="primary-button">Salvar vínculo</button></form></div>`;
        bind();
      };
      const refresh = () => {
        const cr = find('#companyRows'), ur = find('#userRows');
        cr.innerHTML = companies.map(c => editingCompany === c.id ? `<tr data-company-id="${c.id}"><td colspan="4"><form data-company-edit="${c.id}" class="inline-actions"><input class="input" name="name" value="${escape(c.name)}" required maxlength="200"><input class="input" name="slug" value="${escape(c.slug)}" required pattern="[a-z0-9]+(-[a-z0-9]+)*"><button class="primary-button">Salvar</button><button type="button" class="outline-button" data-cancel-company>Cancelar</button></form></td></tr>` : `<tr data-company-id="${c.id}"><td>${escape(c.name)}</td><td>${escape(c.slug)}</td><td>${badge(c.active,'Ativa','Inativa')}</td><td><div class="inline-actions"><button class="outline-button" data-edit-company="${c.id}">Editar</button><button class="outline-button" data-identity-company="${c.id}">Identidade e e-mails</button><button class="outline-button" data-toggle-company="${c.id}">${c.active ? 'Desativar' : 'Ativar'}</button></div></td></tr>`).join('');
        ur.innerHTML = users.map(u => editingUser === u.id ? `<tr data-user-id="${u.id}"><td colspan="4"><form data-user-edit="${u.id}" class="inline-actions"><input class="input" name="name" value="${escape(u.name)}" required maxlength="200"><input class="input" name="email" value="${escape(u.email)}" type="email" required maxlength="254"><button class="primary-button">Salvar</button><button type="button" class="outline-button" data-cancel-user>Cancelar</button></form></td></tr>` : `<tr data-user-id="${u.id}"><td>${escape(u.name)}</td><td>${escape(u.email)}</td><td>${badge(u.active,'Ativo','Inativo')}</td><td><div class="inline-actions"><button class="outline-button" data-edit-user="${u.id}">Editar</button><button class="outline-button" data-reset-user="${u.id}">Redefinir senha</button><button class="outline-button" data-toggle-user="${u.id}">${u.active ? 'Desativar' : 'Ativar'}</button></div></td></tr>`).join('');
        const userId = find('#memberUser').value, companyId = find('#memberCompany').value;
        find('#memberUser').innerHTML = options(users,u=>`${u.name} (${u.email})`); find('#memberCompany').innerHTML = options(companies,c=>`${c.name} (${c.active?'Ativa':'Inativa'})`);
        if (users.some(u=>String(u.id)===userId)) find('#memberUser').value=userId; if (companies.some(c=>String(c.id)===companyId)) find('#memberCompany').value=companyId;
      };
      const openSettings = async id => {
        const c=companies.find(x=>x.id===id), host=find('#globalCompanySettings');
        host.classList.remove('hidden');
        host.innerHTML=`<h3>${escape(c.name)}</h3><form id="emailPolicyForm" class="login-stack"><label>E-mail administrativo<input class="input" name="admin_email" type="email" value="${escape(c.admin_email||'')}"></label><label>Domínios autorizados (um por linha)<textarea class="input" name="email_domains">${escape(c.email_domains.join('\n'))}</textarea></label><label>Exceções de e-mail (uma por linha)<textarea class="input" name="email_exceptions">${escape(c.email_exceptions.join('\n'))}</textarea></label><p>Sem domínios configurados, novos e-mails não têm restrição. Contas existentes são preservadas.</p><button class="primary-button">Salvar configuração</button></form><div id="globalLogoEditor"></div>`;
        find('#emailPolicyForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;const lines=value=>value.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);
          run(f,async()=>{const updated=await request(`/companies/${id}`,'PATCH',{admin_email:f.elements.admin_email.value||null,email_domains:lines(f.elements.email_domains.value),email_exceptions:lines(f.elements.email_exceptions.value)});companies=companies.map(x=>x.id===id?updated:x);return 'Configuração salva.';});
        };
        await window.TAGCHECK_IDENTITY.mount(find('#globalLogoEditor'),c,`/companies/${id}/logo`,request,escape,async()=>{companies=await request('/companies');await refreshIdentity();});
      };
      const showLink = () => { const link=links.find(x=>String(x.company_id)===find('#memberCompany').value); find('#memberRole').value=link?.role||'viewer'; find('#memberActive').checked=link?link.active:true; find('#membershipStatus').innerHTML=link?`Vínculo <span class="status-pill ${link.active?'status-ok':'status-danger'}">${link.active?'ativo':'inativo'}</span>`:'Sem vínculo cadastrado'; };
      let linkVersion=0; const loadLinks=async()=>{const version=++linkVersion; const id=find('#memberUser').value; links=id?await request(`/users/${id}/companies`):[]; if(version===linkVersion)showLink();};
      const bind = () => { find('#backToAdmin').onclick=back; refresh(); loadLinks();
        find('#companyRows').onclick=event=>{const settings=event.target.closest('[data-identity-company]');if(settings){openSettings(Number(settings.dataset.identityCompany));return;}const e=event.target.closest('[data-edit-company]'),t=event.target.closest('[data-toggle-company]'),c=e||t?companies.find(x=>x.id===Number((e||t).dataset[e?'editCompany':'toggleCompany'])):null;if(e){editingCompany=c.id;refresh();}else if(t)run(t,async()=>{const u=await request(`/companies/${c.id}`,'PATCH',{active:!c.active});companies=companies.map(x=>x.id===u.id?u:x);refresh();});else if(event.target.closest('[data-cancel-company]')){editingCompany=null;refresh();}};
        find('#companyRows').onsubmit=event=>{const f=event.target.closest('[data-company-edit]');if(!f)return;event.preventDefault();const c=companies.find(x=>x.id===Number(f.dataset.companyEdit)), data=Object.fromEntries(new FormData(f));run(f,async()=>{const u=await request(`/companies/${c.id}`,'PATCH',data);companies=companies.map(x=>x.id===u.id?u:x);editingCompany=null;refresh();});};
        find('#userRows').onclick=event=>{const e=event.target.closest('[data-edit-user]'),r=event.target.closest('[data-reset-user]'),t=event.target.closest('[data-toggle-user]'),u=(e||r||t)?users.find(x=>x.id===Number((e||r||t).dataset[e?'editUser':r?'resetUser':'toggleUser'])):null;if(e){editingUser=u.id;refresh();}else if(t)run(t,async()=>{const v=await request(`/users/${u.id}`,'PATCH',{active:!u.active});users=users.map(x=>x.id===v.id?v:x);refresh();});else if(r){const password=prompt('Nova senha (mínimo de 12 caracteres)');if(password===null)return;const confirmation=prompt('Confirme a nova senha');if(password!==confirmation||password.length<12){feedback('As senhas devem coincidir e ter pelo menos 12 caracteres.');return;}run(r,async()=>{await request(`/users/${u.id}/reset-password`,'POST',{password});return 'Senha redefinida com sucesso.';});}else if(event.target.closest('[data-cancel-user]')){editingUser=null;refresh();}};
        find('#userRows').onsubmit=event=>{const f=event.target.closest('[data-user-edit]');if(!f)return;event.preventDefault();const u=users.find(x=>x.id===Number(f.dataset.userEdit)), data=Object.fromEntries(new FormData(f));run(f,async()=>{const v=await request(`/users/${u.id}`,'PATCH',data);users=users.map(x=>x.id===v.id?v:x);editingUser=null;refresh();});};
        find('#companyCreateForm').onsubmit=event=>{event.preventDefault();const f=event.currentTarget,data=Object.fromEntries(new FormData(f));run(f,async()=>{companies.push(await request('/companies','POST',data));f.reset();refresh();});};
        find('#userCreateForm').onsubmit=event=>{event.preventDefault();const f=event.currentTarget,d=Object.fromEntries(new FormData(f));f.elements.password.value='';run(f,async()=>{users.push(await request('/users','POST',d));f.reset();refresh();});};
        find('#memberUser').onchange=loadLinks;find('#memberCompany').onchange=showLink;find('#membershipForm').onsubmit=event=>{event.preventDefault();const id=find('#memberUser').value;run(event.currentTarget,async()=>{const l=await request(`/users/${id}/companies`,'POST',{company_id:Number(find('#memberCompany').value),role:find('#memberRole').value,active:find('#memberActive').checked});links=links.filter(x=>x.company_id!==l.company_id).concat(l);showLink();});};
      };
      render();
    } catch (error) { if (panel.isConnected) { panel.innerHTML=`<div class="card panel"><p role="alert">${escape(error.message)}</p><button class="outline-button">Voltar aos equipamentos</button></div>`; panel.querySelector('button').onclick=back; } }
  }
};
